- hosts: localhost
  become: true
  pre_tasks:
    - name: Update cache
      apt:
        update_cache: true
      tags:
        - node
        - zsh
        - 1p
  tasks: 
    - include_tasks:
        file: setup-tasks/zsh.yml
        apply:
          tags:
            - zsh
    - include_tasks:
        file: setup-tasks/node.yml
        apply:
          tags:
            - node
    - include_tasks:
        file: setup-tasks/1p.yml
        apply:
          tags:
            - 1p
