- hosts: localhost
  become: true
  pre_tasks:
    - name: Update cache
      apt:
        update_cache: true
      tags:
        - node
        - zsh
        - 1p
  tasks: 
    - include_tasks: setup-tasks/zsh.yml
    - include_tasks: setup-tasks/node.yml
    - include_tasks: setup-tasks/1p.yml
