- hosts: localhost
  become: true
  pre_tasks:
    - name: Update cache
      apt:
        update_cache: true
      tags:
        - node
        - zsh
  tasks: 
    - include_tasks: setup-tasks/zsh.yml
    - include_tasks: setup-tasks/node.yml
